# Generated by Django 4.0.5 on 2022-06-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
