# Generated by Django 4.0.5 on 2022-06-30 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0003_alter_persona_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
