# Generated by Django 4.0.5 on 2022-06-30 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0006_alter_persona_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='fecha',
            field=models.CharField(max_length=20),
        ),
    ]
